### ISSUE TITLE
Spectral flux in Power3Dcomponent and Power widgets

### ISSUE THREAD

**Issue by jureyherrera** [oasys-kit/XOPPY#84]
There are many **XOPPY** users that are very interested in calculating the **flux in function of the energy** from a source after a specific optical element (e.g. a slit or filter) , in the present both Power widgets provides already the spectral power in function of the energy. 
- Power3Dcomponent:
![image](https://user-images.githubusercontent.com/31166917/92477898-a9fbab80-f1e1-11ea-8ca2-2962ba725844.png)
- Power:
![image](https://user-images.githubusercontent.com/31166917/92478199-1bd3f500-f1e2-11ea-9e37-713f83683a3f.png)

It could be interesting to, in addition, present the flux in function of the energy. For example, it would make it much easier to get the emission spectra from a non-periodic magnetic field wiggler at a given slit, exploiting the new Wiggler Radiation widget:
![image](https://user-images.githubusercontent.com/31166917/92480770-a66a2380-f1e5-11ea-95bd-b7529a6c9cb2.png)

Thank you in advance for your attention. Kind regards

**Comment by srio** [comment]
Good idea to use wiggler_radiation to get wiggler flux on slit!!

OK it is implemented. 

I also changed the labels in power to "Power density [W/eV]" if input from Oasys wire otherwise arbitrary units "Power density [a.u.]" if input is 1 or user file (who knows what is in the user file...)

Have a look and if you like it I invite you to close the issue!

Cheers, M

**Comment by jureyherrera** [comment]
The changes on the widgets are very useful and are working pretty neat.

Thanks a lot. Cheers, J
